name: CIChallenge3
env:
    ARTIFACT_NAME: "my-artifact"

on: [ push ]

jobs:
    test-job: 
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code step
            uses: actions/checkout@v4
          - name: test run
            run: python Py_code/hello.py
    
    # build-job:
    #     runs-on: ubuntu-latest
    #     needs: test-job
    #     steps:
    #         - name: Checkout code step
    #           uses: actions/checkout@v4

    #         - name: Upload artifact
    #           uses: actions/upload-artifact@v4
    #           with:
    #             name: ${{ env.ARTIFACT_NAME }}
    #             path: .
            
    
