name: CIChallenge

on: [ push ]

jobs:
    job1:
        runs-on: ubuntu-latest

        steps:
            - name: Print date from Ubuntu
              run: date
    
    job2:
        runs-on: windows-latest

        steps:
            - name: Print date from Windows
              run: date
    
    job3:
        runs-on: macos-latest

        steps:
            - name: Print date from MAcOS
              run: date

    job4:
        runs-on: ubuntu-latest
        needs: [ job1, job2, job3 ]
        steps:
            - name: Print date after all 3 jobs
              run: date
