name: CIChallenge2
env:
    ARTIFACT_NAME: "my-artifact"

on: [ push ]

jobs:
    my-job: 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code step
              uses: actions/checkout@v4

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ env.ARTIFACT_NAME }}
                path: .
            
    
